version: '3.0'
services:
  web:
    build:
      context: .
      dockerfile: build/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/app/
    links:
      - php
  php:
    build:
      context: .
      dockerfile: build/php/Dockerfile
    volumes:
      - .:/app/
